### ISSUE TITLE
Migrations not included on released build v0.2.8

### ISSUE THREAD

**Issue by niedbalski** [Linaro/mr-provisioner#72] opened 2018-01-26 03:27 UTC
The migrations directory hasn't been included as part of the v0.2.8 release file.

Steps to reproduce:

$ virtualenv env -p python3.5 && source env/bin/activate
$ pip install https://github.com/Linaro/mr-provisioner/releases/download/v0.2.8/mr-provisioner-0.2.8.tar.gz
$ mr-provisioner -c /etc/mr-provisioner.ini db upgrade

**Comment by gemagomez** [comment] 2018-01-26 13:42
Duplicate of #70.

**Closed by gemagomez** 2018-01-26 13:42 UTC
