### ISSUE TITLE
Use <title> more

### ISSUE THREAD

**Issue by hrw** [Linaro/mr-provisioner#40] opened 2017-07-24 14:39 UTC
All mlab pages use same <title> value:

![image](https://user-images.githubusercontent.com/185508/28528599-781f7718-708e-11e7-9bf6-71f07b34f899.png)

Having "r1-m1-c38n1 console - mlab-cb", "r1-m1-c38n1 machine - mlab-cb" and "erp-17.08-debian-moonshot preseed - mlab-cb" names would make life easier.

**Comment by gemagomez** [comment] 2017-07-26 05:20
This is a duplicate of #38. Closing.

**Closed by gemagomez** 2017-07-26 05:20 UTC
